/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundo_proyect;

/**
 *
 * @author Laura Sabillon
 */
public class PROFILE extends javax.swing.JFrame {

    private users usuarios;
    private Tweets twits;

    /**
     * Creates new form PROFILE
     */
    public PROFILE() {
        initComponents();
        infoProfile();
    }

    private void infoProfile() {
        USUARIO usuarioActual = logged_in.getEnSesion();
            userTag.setText("@ " + usuarioActual.getUsuario());
            generoProfile.setText(String.valueOf(usuarioActual.getGenero()));
            followersProfile.setText(String.valueOf(usuarioActual.getFollowers()));
            edadProfile.setText(String.valueOf(usuarioActual.getEdad()));
            followingProfile.setText(String.valueOf(usuarioActual.getFollowing()));
            nombreProfile.setText(usuarioActual.getNombre());
 
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        followingProfile = new javax.swing.JLabel();
        TWEETS = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTag = new javax.swing.JLabel();
        generoProfile = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edadProfile = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        followersProfile = new javax.swing.JLabel();
        FOLLOWERS = new javax.swing.JToggleButton();
        FOLLOWING = new javax.swing.JToggleButton();
        CONTAINER = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        search_show = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        RETURN = new javax.swing.JToggleButton();
        go_back = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        nombreProfile = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        followingProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        followingProfile.setText("0");
        getContentPane().add(followingProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 50, 50));

        TWEETS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TWEETS.setText("TWEETS");
        getContentPane().add(TWEETS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 195, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Followers: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 100, 26));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 1057, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segundo_proyect/UsuarioAnonimo (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 150));

        userTag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(userTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 170, 30));

        generoProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(generoProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 40, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Edad:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 26));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Genero:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 100, 26));

        edadProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(edadProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 37, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Following:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 100, 30));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, 230, -1));

        jlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlabel.setText("Nombre: ");
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 90, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Fecha de union: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 150, 26));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("BUSCAR :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 100, 26));

        followersProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(followersProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 60, 30));

        FOLLOWERS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FOLLOWERS.setText("FOLLOWERS");
        getContentPane().add(FOLLOWERS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 195, -1));

        FOLLOWING.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FOLLOWING.setText("FOLLOWING");
        getContentPane().add(FOLLOWING, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 195, -1));
        getContentPane().add(CONTAINER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 590, 260));

        search_show.setColumns(20);
        search_show.setRows(5);
        search_show.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                search_showAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        search_show.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_showKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(search_show);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 350, 320));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segundo_proyect/background_pf.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1060, 250));

        RETURN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RETURN.setText("DESACTIVAR CUENTA");
        RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETURNActionPerformed(evt);
            }
        });
        getContentPane().add(RETURN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 260, -1));

        go_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        go_back.setText("GO BACK");
        go_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_backActionPerformed(evt);
            }
        });
        getContentPane().add(go_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Usuario: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        nombreProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreProfile.setText(" ");
        getContentPane().add(nombreProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 140, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("0");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void search_showKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_showKeyPressed
        // TODO add your handling code here:
        search_show.setEditable(false);
    }//GEN-LAST:event_search_showKeyPressed

    private void RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETURNActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_RETURNActionPerformed

    private void go_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_backActionPerformed
        // TODO add your handling code here:
        MENU_HOME menu = new MENU_HOME(usuarios);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_go_backActionPerformed

    private void search_showAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_search_showAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_search_showAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROFILE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CONTAINER;
    private javax.swing.JToggleButton FOLLOWERS;
    private javax.swing.JToggleButton FOLLOWING;
    private javax.swing.JToggleButton RETURN;
    private javax.swing.JToggleButton TWEETS;
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel edadProfile;
    private javax.swing.JLabel followersProfile;
    private javax.swing.JLabel followingProfile;
    private javax.swing.JLabel generoProfile;
    private javax.swing.JToggleButton go_back;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel nombreProfile;
    private javax.swing.JTextArea search_show;
    private javax.swing.JLabel userTag;
    // End of variables declaration//GEN-END:variables
}
