/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundo_proyect;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristina Sabillon
 */
public class PROFILE extends javax.swing.JFrame {

    private users userDatabase;
    private USUARIO[] usuarios;
    private DefaultListModel<String> lista_usuario;
    private DefaultListModel<String> listaRealUsuarios;

    /**
     * Creates new form PROFILE
     */
    public PROFILE(users userDatabase) {
        this.userDatabase = userDatabase;
        initComponents();

        this.usuarios = userDatabase.getUsuarios();
        lista_usuario = new DefaultListModel<>();
        listaRealUsuarios = new DefaultListModel<>();
        usuarios_showcase.setModel(lista_usuario);
        añadir_A_Jlist();

        lista_usuario.clear();

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                actualizarContadores();
                actualizarTwits();
            }
        });
    }

    private void actualizarContadores() {
        USUARIO userInSession = userDatabase.getUserInSession();
        if (userInSession != null) {
            USUARIO[] followingList = userInSession.getFollowing();
            int activeFollowings = 0;
            for (USUARIO followedUser : followingList) {
                if (followedUser != null && followedUser.getEstado()) {
                    activeFollowings++;
                }
            }
            USUARIO[] followerlist = userInSession.getFollowers();
            int activeFollowers = 0;
            for (USUARIO followingUser : followerlist) {
                if (followingUser != null && followingUser.getEstado()) {
                    activeFollowers++;
                }
            }
            followersProfile1.setText(String.valueOf(activeFollowers));
            followingProfile.setText(String.valueOf(activeFollowings));
        }
    }

    private void actualizarTwits() {
        USUARIO loggedUser = userDatabase.getUserInSession();
        String totalTweets = loggedUser.mostrarTwit();
        this.tweets_user.setText(totalTweets);
    }

    private void añadir_A_Jlist() {
        lista_usuario.clear();
        USUARIO loggedInUser = this.userDatabase.getUserInSession();
        for (USUARIO user : usuarios) {
            if (user != null && user.getEstado() && !loggedInUser.getUsuario().equals(loggedInUser.getUsuario())) {
                lista_usuario.addElement(user.getUsuario());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MostrarFollowers = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        user_showcase = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        MostrarFollowing = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        buscar_personas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DESACTIVAR = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CONTAINER1 = new javax.swing.JScrollPane();
        usuarios_showcase = new javax.swing.JList<>();
        go_back1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tweets_user = new javax.swing.JTextArea();
        followingProfile = new javax.swing.JLabel();
        followersProfile1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MostrarFollowers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MostrarFollowers.setText("Followers: ");
        MostrarFollowers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarFollowersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarFollowersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarFollowersMouseExited(evt);
            }
        });
        getContentPane().add(MostrarFollowers, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 110, 26));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 750, 880, 30));

        perfil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segundo_proyect/male_silouette.jpg"))); // NOI18N
        perfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                perfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 100));

        user_showcase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user_showcase.setText("@");
        user_showcase.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                user_showcaseAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(user_showcase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 160, 20));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gender.setText("o");
        gender.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                genderAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 37, -1));

        edad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edad.setText("Edad:");
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 50, 26));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Genero:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, 26));

        age.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        age.setText("o");
        age.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ageAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 37, -1));

        MostrarFollowing.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MostrarFollowing.setText("Following: ");
        MostrarFollowing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarFollowingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MostrarFollowingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MostrarFollowingMouseExited(evt);
            }
        });
        getContentPane().add(MostrarFollowing, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, 110, 30));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre.setText("Nombre: ");
        nombre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nombreAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 360, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Fecha de union: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 146, 26));

        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.setText("0");
        date.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 150, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segundo_proyect/background_pf.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 220));

        usuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuario1.setText("Usuario:");
        getContentPane().add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 40));

        buscar_personas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar_personasKeyReleased(evt);
            }
        });
        getContentPane().add(buscar_personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 280, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("BUSCAR PERSONAS: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 425, -1, 40));

        DESACTIVAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DESACTIVAR.setText("DESACTIVAR CUENTA");
        DESACTIVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESACTIVARActionPerformed(evt);
            }
        });
        getContentPane().add(DESACTIVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 260, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Tweets:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 150, 30));

        jScrollPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPane1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        usuarios_showcase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuarios_showcase.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                usuarios_showcaseAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        usuarios_showcase.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                usuarios_showcaseValueChanged(evt);
            }
        });
        CONTAINER1.setViewportView(usuarios_showcase);

        jScrollPane1.setViewportView(CONTAINER1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 280, 180));

        go_back1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        go_back1.setText("GO BACK");
        go_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_back1ActionPerformed(evt);
            }
        });
        getContentPane().add(go_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 260, -1));

        tweets_user.setColumns(20);
        tweets_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tweets_user.setRows(5);
        jScrollPane2.setViewportView(tweets_user);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 460, 240));

        followingProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        followingProfile.setText("0");
        getContentPane().add(followingProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, -1, -1));

        followersProfile1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        followersProfile1.setText("0");
        getContentPane().add(followersProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ageAncestorAdded
        // TODO add your handling code here:
        USUARIO userInSession = userDatabase.getUserInSession();
        if (userInSession != null) {
            int edad = userInSession.getEdad();
            age.setText(String.valueOf(edad));
        } else {
            age.setText("NoN");
        }
    }//GEN-LAST:event_ageAncestorAdded

    private void genderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_genderAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            char genero = usuario.getGenero();
            gender.setText(String.valueOf(genero));
        } else {
            gender.setText("NoN");
        }
    }//GEN-LAST:event_genderAncestorAdded

    private void dateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            Calendar fecha = usuario.getFecha();
            if (fecha != null) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String fechaString = dateFormat.format(fecha.getTime());
                date.setText(fechaString);
            }
        } else {
            date.setText("NoN");
        }
    }//GEN-LAST:event_dateAncestorAdded

    private void perfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_perfilAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            char genero = usuario.getGenero();
            ImageIcon icon = null;

            try {
                if (genero == 'M') {
                    icon = new ImageIcon(getClass().getResource("/segundo_proyect/male_silouette.jpg"));
                } else if (genero == 'F') {
                    icon = new ImageIcon(getClass().getResource("/segundo_proyect/female_silouette.jpg"));
                }
                if (icon.getImageLoadStatus() != java.awt.MediaTracker.COMPLETE) {
                    System.err.println("Error al cargar la imagen: " + icon.getDescription());
                }
            } catch (Exception e) {
                System.err.println("Error al cargar la imagen: " + e.getMessage());
            }

            if (icon != null) {
                perfil.setIcon(icon);
            }
        }
    }//GEN-LAST:event_perfilAncestorAdded

    private void user_showcaseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_user_showcaseAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            String username = usuario.getUsuario();
            user_showcase.setText("@" + username);
        } else {
            user_showcase.setText("NoN");
        }
    }//GEN-LAST:event_user_showcaseAncestorAdded

    private void nombreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nombreAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            String username = usuario.getNombre();
            nombre.setText("Nombre: " + username);
        } else {
            nombre.setText("Nombre: NoN");
        }
    }//GEN-LAST:event_nombreAncestorAdded

    private void DESACTIVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESACTIVARActionPerformed
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            int response = JOptionPane.showConfirmDialog(
                    null,
                    "Desea desactivar su cuenta?",
                    "Confirmacion de Desactivacion de Cuenta",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (response == JOptionPane.YES_OPTION) {
                usuario.setEstado(false);
                usuario.setEnSession(false);

                JOptionPane.showMessageDialog(null, "Su cuenta ha sido desactivada.");
                LOG_in log = new LOG_in(this.userDatabase);
                log.setVisible(true);
                this.dispose();
            } else if (response == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "La desactivación de la cuenta ha sido cancelada.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay ningún usuario en sesión.");
        }
    }//GEN-LAST:event_DESACTIVARActionPerformed

    private void usuarios_showcaseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usuarios_showcaseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarios_showcaseAncestorAdded

    private void usuarios_showcaseValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_usuarios_showcaseValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            int selectedIndex = usuarios_showcase.getSelectedIndex();
            if (selectedIndex != -1) {
                String selectedUsername = listaRealUsuarios.getElementAt(selectedIndex);
                if (selectedUsername != null) {
                    Profile_otro_usuario otro = new Profile_otro_usuario(this.userDatabase, selectedUsername);
                    otro.setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_usuarios_showcaseValueChanged

    private void jScrollPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1AncestorAdded

    private void go_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_back1ActionPerformed
        // TODO add your handling code here:
        MENU_HOME MENU = new MENU_HOME(this.userDatabase);
        MENU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_go_back1ActionPerformed

    private void MostrarFollowingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarFollowingMouseClicked

        USUARIO user = this.userDatabase.getUserInSession();

        USUARIO[] followingList = user.getFollowing();
        int numeroSeguidos = user.getFollowingCount();

        String FOLLOWING = "Usuarios que sigues:\n";
        int activeFollowingCount = 0;

        for (int contador = 0; contador < numeroSeguidos; contador++) {
            USUARIO followedUser = followingList[contador];
            if (followedUser != null && followedUser.getEstado()) {
                FOLLOWING += followedUser.getUsuario() + "\n";
                activeFollowingCount++;
            }
        }

        if (activeFollowingCount == 0) {
            FOLLOWING += "No sigues a nadie.";
        }

        JOptionPane.showMessageDialog(null, FOLLOWING);

    }//GEN-LAST:event_MostrarFollowingMouseClicked

    private void MostrarFollowersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarFollowersMouseClicked

        USUARIO user = this.userDatabase.getUserInSession();
        USUARIO[] followersList = user.getFollowers();
        int numeroSeguidores = user.getFollowersCount();

        String FOLLOWERS = "Usuarios que te siguen:\n";
        int activeFollowersCount = 0;

        for (int contador = 0; contador < numeroSeguidores; contador++) {
            USUARIO followerUser = followersList[contador];
            if (followerUser != null && followerUser.getEstado()) {
                FOLLOWERS += followerUser.getUsuario() + "\n";
                activeFollowersCount++;
            }
        }

        if (activeFollowersCount == 0) {
            FOLLOWERS += "No te sigue nadie.";
        }

        JOptionPane.showMessageDialog(null, FOLLOWERS);

    }//GEN-LAST:event_MostrarFollowersMouseClicked

    private void buscar_personasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar_personasKeyReleased
        String buscar = buscar_personas.getText().trim().toLowerCase();

        USUARIO loggedInUser = this.userDatabase.getUserInSession();

        lista_usuario.clear();
        listaRealUsuarios.clear();

        if (buscar.isEmpty()) {
            lista_usuario.clear();
            listaRealUsuarios.clear();
        } else if (usuarios != null) {
            for (USUARIO user : usuarios) {
                if (user != null && user.getUsuario() != null) {
                    if (user.getUsuario().toLowerCase().contains(buscar) && user.getEstado() && !user.equals(loggedInUser)) {
                        String nombreUsuarioReal = user.getUsuario(); 
                        String nombreParaMostrar = nombreUsuarioReal;

                        USUARIO[] followingList = loggedInUser.getFollowing();
                        boolean founduser=false;
                        for (USUARIO followedUser : followingList) {
                            if (followedUser != null && followedUser.equals(user) && followedUser.getEstado()) {
                                founduser=true;
                                break;
                            }
                        }
                        if (founduser) {
                            nombreParaMostrar += " - following";
                        }else{
                            nombreParaMostrar += " - Not following";
                        }
                        listaRealUsuarios.addElement(nombreUsuarioReal);
                        lista_usuario.addElement(nombreParaMostrar);
                    }
                }
            }
        }
    }//GEN-LAST:event_buscar_personasKeyReleased

    private void MostrarFollowersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarFollowersMouseEntered

        MostrarFollowers.setForeground(Color.blue);
    }//GEN-LAST:event_MostrarFollowersMouseEntered

    private void MostrarFollowersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarFollowersMouseExited

        MostrarFollowers.setForeground(Color.black);
    }//GEN-LAST:event_MostrarFollowersMouseExited

    private void MostrarFollowingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarFollowingMouseEntered

        MostrarFollowing.setForeground(Color.blue);
    }//GEN-LAST:event_MostrarFollowingMouseEntered

    private void MostrarFollowingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarFollowingMouseExited

        MostrarFollowing.setForeground(Color.black);
    }//GEN-LAST:event_MostrarFollowingMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        users userDatabase = new users(100);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROFILE(userDatabase).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CONTAINER1;
    private javax.swing.JToggleButton DESACTIVAR;
    private javax.swing.JLabel MostrarFollowers;
    private javax.swing.JLabel MostrarFollowing;
    private javax.swing.JLabel age;
    private javax.swing.JTextField buscar_personas;
    private javax.swing.JLabel date;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel followersProfile1;
    private javax.swing.JLabel followingProfile;
    private javax.swing.JLabel gender;
    private javax.swing.JToggleButton go_back1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel perfil;
    private javax.swing.JTextArea tweets_user;
    private javax.swing.JLabel user_showcase;
    private javax.swing.JLabel usuario1;
    private javax.swing.JList<String> usuarios_showcase;
    // End of variables declaration//GEN-END:variables
}
