/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundo_proyect;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
/**
 *
 * @author Laura Sabillon
 */
public class PROFILE extends javax.swing.JFrame {
    private users userDatabase;
    private Tweets twits;

    /**
     * Creates new form PROFILE
     */
    public PROFILE(users userDatabase) {
        this.userDatabase = userDatabase;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TWEETS = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        usersss = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        CONTAINER = new javax.swing.JScrollPane();
        jLabel17 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        CONTAINER1 = new javax.swing.JScrollPane();
        usuarios_showcase = new javax.swing.JList<>();
        buscar_personas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        go_back1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TWEETS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TWEETS.setText("TWEETS");
        TWEETS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWEETSActionPerformed(evt);
            }
        });
        getContentPane().add(TWEETS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 430, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Followers: 0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 120, 26));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 750, 880, 30));

        perfil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segundo_proyect/male_silouette.jpg"))); // NOI18N
        perfil.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                perfilAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 100));

        usersss.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usersss.setText("@");
        usersss.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                usersssAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(usersss, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 20));

        gender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gender.setText("o");
        gender.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                genderAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 37, -1));

        edad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edad.setText("Edad:");
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 50, 26));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Genero:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 26));

        age.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        age.setText("o");
        age.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ageAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 37, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Following: 0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 120, 26));

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombre.setText("Nombre: ");
        nombre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nombreAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 360, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Fecha de union: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 146, 26));

        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.setText("0");
        date.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 150, -1));
        getContentPane().add(CONTAINER, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 430, 240));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/segundo_proyect/background_pf.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 220));

        usuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usuario1.setText("Usuario:");
        getContentPane().add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 100, -1));

        usuarios_showcase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarios_showcase.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        usuarios_showcase.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                usuarios_showcaseAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CONTAINER1.setViewportView(usuarios_showcase);

        getContentPane().add(CONTAINER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 430, 240));

        buscar_personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_personasActionPerformed(evt);
            }
        });
        getContentPane().add(buscar_personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 240, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("BUSCAR PERSONAS: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        go_back1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        go_back1.setText("GO BACK");
        go_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_back1ActionPerformed(evt);
            }
        });
        getContentPane().add(go_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 260, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ageAncestorAdded
        // TODO add your handling code here:
        USUARIO userInSession = userDatabase.getUserInSession();
        if (userInSession != null) {
            int edad = userInSession.getEdad();
            age.setText(String.valueOf(edad));
        } else {
            age.setText("NoN");
        }
    }//GEN-LAST:event_ageAncestorAdded

    private void genderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_genderAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            char genero = usuario.getGenero();
            gender.setText(String.valueOf(genero));
        } else {
            gender.setText("NoN");
        }               
    }//GEN-LAST:event_genderAncestorAdded

    private void dateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            Calendar fecha = usuario.getFecha();
            if (fecha != null) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String fechaString = dateFormat.format(fecha.getTime());
                date.setText(fechaString);
            }
        } else {
            date.setText("NoN");
        }
    }//GEN-LAST:event_dateAncestorAdded

    private void perfilAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_perfilAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
         if (usuario != null) {
             char genero = usuario.getGenero();
             ImageIcon icon = null;

             try {
                 if (genero == 'M') {
                     icon = new ImageIcon(getClass().getResource("/segundo_proyect/male_silouette.jpg"));
                 } else if (genero == 'F') {
                     icon = new ImageIcon(getClass().getResource("/segundo_proyect/female_silouette.jpg"));
                 }

                 if (icon.getImageLoadStatus() != java.awt.MediaTracker.COMPLETE) {
                     System.err.println("Error al cargar la imagen: " + icon.getDescription());
                 }
             } catch (Exception e) {
                 System.err.println("Error al cargar la imagen: " + e.getMessage());
             }

             if (icon != null) {
                 perfil.setIcon(icon);
             }
         }
    }//GEN-LAST:event_perfilAncestorAdded

    private void usersssAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usersssAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            String username = usuario.getUsuario();
            usersss.setText("@" + username);
        } else {
            usersss.setText("NoN");
        }
    }//GEN-LAST:event_usersssAncestorAdded

    private void TWEETSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWEETSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TWEETSActionPerformed

    private void nombreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nombreAncestorAdded
        // TODO add your handling code here:
        USUARIO usuario = userDatabase.getUserInSession();
        if (usuario != null) {
            String username = usuario.getNombre();
            nombre.setText("Nombre: " + username);
        } else {
            nombre.setText("Nombre: NoN");
        }        
    }//GEN-LAST:event_nombreAncestorAdded

    private void buscar_personasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_personasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_buscar_personasActionPerformed

    private void go_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_back1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_go_back1ActionPerformed

    private void usuarios_showcaseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usuarios_showcaseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarios_showcaseAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROFILE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        users userDatabase = new users(100);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROFILE(userDatabase).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CONTAINER;
    private javax.swing.JScrollPane CONTAINER1;
    private javax.swing.JToggleButton TWEETS;
    private javax.swing.JLabel age;
    private javax.swing.JTextField buscar_personas;
    private javax.swing.JLabel date;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel gender;
    private javax.swing.JToggleButton go_back1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel perfil;
    private javax.swing.JLabel usersss;
    private javax.swing.JLabel usuario1;
    private javax.swing.JList<String> usuarios_showcase;
    // End of variables declaration//GEN-END:variables
}
